apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: nats_jetstream_consumer_pending_messages
        target:
          type: AverageValue
          averageValue: {{ .Values.worker.autoscaling.targetQueueSize }}